### PR TITLE
Highmass optional

### PR DESCRIPTION
**Pull request by bjfultn**
Only omit the Mpsini << Mstar assumption when Mpsini > 10% * Mstar. @zhexingli please test this in your high-mass (binary star) case to confirm that it works for that.

### CODE REVIEW

**Comment by bjfultn** [comment]
Nevermind, the numbers aren't working out yet. Will re-open when ready for testing.

**Comment by bjfultn** [comment]
OK, should be ready for testing now.

**Comment by zhexingli** [comment]
Ok I'll take a look in in the next few days and let you know.

**Comment by zhexingli** [comment]
Just tested, it runs perfectly. It's able to correct Mpsini calculation for high mass and values derived are correct. I presume it works as well for lower mass end?

**Pull request merged**
